# Generated by Django 6.0.6 on 2026-07-06 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('quick_edit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDFAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('page_number', models.IntegerField(help_text='0-indexed page number for MuPDF compatibility')),
                ('annotation_type', models.CharField(choices=[('pen', 'Pen'), ('highlighter', 'Highlighter'), ('text', 'Text'), ('stamp', 'Stamp'), ('cloud', 'Cloud')], max_length=20)),
                ('color_r', models.FloatField(blank=True, null=True)),
                ('color_g', models.FloatField(blank=True, null=True)),
                ('color_b', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='sherbert_pdf.pdfdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PenAnnotationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('vertices', models.JSONField(help_text='Array of points: [[[x1,y1], [x2,y2], ...]]')),
                ('border_width', models.FloatField(default=1.0)),
                ('opacity', models.FloatField(default=1.0)),
                ('erasures', models.JSONField(blank=True, default=list, help_text='Eraser circles in PDF coords: [{cx, cy, r}]')),
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pen_data', to='sherbert_pdf.pdfannotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StampAnnotationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('image_url', models.CharField(max_length=500)),
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_data', to='sherbert_pdf.pdfannotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextAnnotationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('rect_x1', models.FloatField()),
                ('rect_y1', models.FloatField()),
                ('rect_x2', models.FloatField()),
                ('rect_y2', models.FloatField()),
                ('content', models.TextField()),
                ('font_size', models.IntegerField(default=16)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=255)),
                ('font_style', models.CharField(default='normal', max_length=20)),
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_data', to='sherbert_pdf.pdfannotation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
