# Generated by Django 6.0.6 on 2026-07-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_book_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view_ordered_from', 'Can view ordered from field'), ('can_check_out', 'Can check out a book')], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
